skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stax = "DWqrx3j2gJYGEc4VfB1RjRtu4K8fx32Font6DWhckm6i"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
